# Generated by Django 5.1.1 on 2024-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pages.tag', verbose_name='Etiquetas'),
        ),
    ]
